#!/usr/bin/env bash
# Shared helpers for install.sh and the per-host manifests in hosts/<host>/host.sh.

DRY_RUN="${DRY_RUN:-0}"

log()  { printf '  %s\n' "$*"; }
head_() { printf '\n==> %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }
die()  { printf 'Error: %s\n' "$*" >&2; exit 1; }

run() {
  if [ "$DRY_RUN" = "1" ]; then
    return 0
  fi
  "$@"
}

# link_file <src> <dest> — symlink dest -> src, backing up anything in the way.
link_file() {
  local src="$1" dest="$2"

  if [ -L "$dest" ]; then
    local current_target
    current_target="$(readlink "$dest")"
    if [ "$current_target" = "$src" ]; then
      log "ok: $dest"
      return
    fi
    log "updating: $dest (was → $current_target)"
    run rm "$dest"
  elif [ -e "$dest" ]; then
    log "backing up: $dest → ${dest}.bak"
    run mv "$dest" "${dest}.bak"
  fi

  run mkdir -p "$(dirname "$dest")"
  run ln -s "$src" "$dest"
  log "linked: $dest → $src"
}

# link_tree <src_dir> <dest_dir> — mirror every file of src_dir into dest_dir
# as a symlink, preserving the relative layout. No-op if src_dir is absent.
link_tree() {
  local src_dir="$1" dest_dir="$2" f rel
  [ -d "$src_dir" ] || return 0
  while IFS= read -r f; do
    rel="${f#"$src_dir"/}"
    link_file "$f" "$dest_dir/$rel"
  done < <(find "$src_dir" -type f ! -name '.DS_Store' | sort)
}

# prune_links <dir> <dotfiles_dir> — drop symlinks in dir that point into the
# dotfiles repo but no longer resolve (files renamed or removed upstream).
prune_links() {
  local dir="$1" root="$2" f target
  [ -d "$dir" ] || return 0
  while IFS= read -r f; do
    target="$(readlink "$f")"
    case "$target" in
      "$root"/*) [ -e "$f" ] || { log "pruning stale link: $f"; run rm "$f"; } ;;
    esac
  done < <(find "$dir" -maxdepth 1 -type l)
}

# merge_files <dest> <src>... — concatenate the bodies of JSON-array fragments
# (everything between the lone `[` and the lone `]`) into a single array.
# Writes a real file, not a symlink, and only when the content changes.
merge_json_arrays() {
  local dest="$1"; shift
  local tmp f
  tmp="$(mktemp)"
  {
    echo "// GENERATED by install.sh — do not edit, your changes will be overwritten."
    for f in "$@"; do
      echo "// source: ${f#"$DOTFILES_DIR"/}"
    done
    echo "["
    for f in "$@"; do
      sed -e '1,/^\[[[:space:]]*$/d' -e '/^\][[:space:]]*$/,$d' "$f"
    done
    echo "]"
  } > "$tmp"

  if [ -L "$dest" ]; then
    log "replacing symlink with generated file: $dest"
    run rm "$dest"
  elif [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
    log "ok: $dest (generated)"
    rm -f "$tmp"
    return
  elif [ -e "$dest" ] && ! grep -q '^// GENERATED by install.sh' "$dest"; then
    log "backing up: $dest → ${dest}.bak"
    run mv "$dest" "${dest}.bak"
  fi

  if [ "$DRY_RUN" = "1" ]; then
    log "would generate: $dest"
    rm -f "$tmp"
    return
  fi
  mkdir -p "$(dirname "$dest")"
  mv "$tmp" "$dest"
  chmod 644 "$dest"
  log "generated: $dest"
}
